volumes:
    public_html_volume:
    storage_volume:
    database_volume:
    redis_volume:

services:
    app:
        image: secure-proxy:latest
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "public_html_volume:/var/www/html/public"
            - "storage_volume:/var/www/html/storage"
        environment: &app_environments
            TZ: ${TZ:-Asia/Tehran}
            APP_KEY: ${APP_KEY}
            APP_DEBUG: ${APP_DEBUG-false}
            APP_ENV: ${APP_ENV-production}
            CONTAINER_ROLE: "PHP-FPM"
            DB_CONNECTION: mysql
            DB_HOST: database
            DB_DATABASE: laravel
            DB_USERNAME: root
            DB_PASSWORD: password
            REDIS_HOST: redis
            SESSION_DRIVER: redis
            QUEUE_CONNECTION: redis
            CACHE_STORE: redis


    queue:
        image: secure-proxy:latest
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "public_html_volume:/var/www/html/public"
        environment:
            <<: *app_environments
            CONTAINER_ROLE: "QUEUE"

    scheduler:
        image: secure-proxy:latest
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "public_html_volume:/var/www/html/public"
        environment:
            <<: *app_environments
            CONTAINER_ROLE: "SCHEDULER"

    webserver:
        image: nginx:latest
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
            - "public_html_volume:/var/www/html/public:ro"
        ports:
            - "8080:80"

    database:
        image: mariadb:latest
        volumes:
            - "database_volume:/var/lib/mysql:Z"
        environment:
            TZ: Asia/Tehran
            MARIADB_ROOT_PASSWORD: password
            MARIADB_AUTO_UPGRADE: 1
            MARIADB_DATABASE: laravel

    redis:
        image: redis:alpine
        volumes:
            - "redis_volume:/data"
        environment:
            TZ: Asia/Tehran

    dns:
        image: dns_reverse_proxy:latest
        ports:
            - "53:53"
        command:
            -  "--endpoint http://app/api/resolve"

    proxy:
        image: secureforward-proxy:latest
        ports:
            - "80:80"
            - "443:443"
